function set_grid_size(){
	with control{
		chunk_xsize = ceil(xsize / CHUNK_WIDTH)
		chunk_ysize = ceil(ysize / CHUNK_HEIGHT)
		null_edificio.coordenadas_dis = ds_grid_create(xsize, ysize)
		ds_grid_clear(null_edificio.coordenadas_dis, 0)
		blueprint_grid = ds_grid_create(xsize, ysize)
		ds_grid_clear(blueprint_grid, false)
		edificio_bool = ds_grid_create(xsize, ysize)
		ds_grid_clear(edificio_bool, false)
		edificio_id = ds_grid_create(xsize, ysize)
		ds_grid_clear(edificio_id, null_edificio)
		edificio_draw = ds_grid_create(xsize, ysize)
		ds_grid_clear(edificio_draw, false)
		ore = ds_grid_create(xsize, ysize)
		ds_grid_clear(ore, -1)
		ore_amount = ds_grid_create(xsize, ysize)
		ds_grid_clear(ore_amount, 0)
		ore_random = ds_grid_create(xsize, ysize)
		ds_grid_clear(ore_random, 0)
		terreno = ds_grid_create(xsize, ysize)
		ds_grid_clear(terreno, 1)
		edificio_cercano = ds_grid_create(xsize, ysize)
		ds_grid_clear(edificio_cercano, null_edificio)
		edificio_cercano_dis = ds_grid_create(xsize, ysize)
		ds_grid_clear(edificio_cercano_dis, infinity)
		edificio_cercano_dir = ds_grid_create(xsize, ysize)
		ds_grid_clear(edificio_cercano_dir, -1)
		edificio_cercano_priority = ds_grid_create(xsize, ysize)
		pre_abtoxy = ds_grid_create(xsize + 2, ysize + 2)
		ds_grid_clear(pre_abtoxy, [0, 0])
		var a, b, a2, a3, temp_priority, temp_complex, edificio
		for(a = 0; a < xsize; a++){
			a2 = a + 0.5
			a3 = a + 1
			ds_grid_set(pre_abtoxy, a, 0, [a2 * 48 + 16, 0])
			ds_grid_set(pre_abtoxy, a, ysize + 1, [a2 * 48 + 16, (ysize + 2) * 14])
			for(b = 0; b < ysize; b++){
				temp_priority = ds_priority_create()
				ds_priority_add(temp_priority, null_edificio, 0)
				ds_priority_delete_max(temp_priority)
				ds_grid_set(edificio_cercano_priority, a, b, temp_priority)
				temp_complex = [real(a + (b mod 2) / 2) * 48 + 16, real(b + 1) * 14]
				ds_grid_set(pre_abtoxy, a3, b + 1, temp_complex)
				ds_grid_set(ore_random, a, b, random(1))
			}
		}
		for(b = 0; b < ysize; b++){
			ds_grid_set(pre_abtoxy, 0, b, [real((b mod 2) / 2) * 48 + 16, real(b + 1) * 14])
			ds_grid_set(pre_abtoxy, xsize + 1, b, [real(xsize + 1 + (b mod 2) / 2) * 48 + 16, real(b + 1) * 14])
		}
		terreno_pared_index = ds_grid_create(xsize, ysize)
		ds_grid_clear(terreno_pared_index, 0)
		repair_id = ds_grid_create(xsize, ysize)
		ds_grid_clear(repair_id, -1)
		repair_dir = ds_grid_create(xsize, ysize)
		ds_grid_clear(repair_dir, 0)
		repair_mode = ds_grid_create(xsize, ysize)
		ds_grid_clear(repair_mode, false)
		repair_select = ds_grid_create(xsize, ysize)
		ds_grid_clear(repair_select, 0)
		background_bool = ds_grid_create(chunk_xsize, chunk_ysize)
		ds_grid_clear(background_bool, false)
		usable_grid_bool = ds_grid_create(xsize, ysize)
		ds_grid_clear(usable_grid_bool, false)
		grid_water_distance = ds_grid_create(xsize, ysize)
		ds_grid_clear(grid_water_distance, infinity)
		background = ds_grid_create(chunk_xsize, chunk_ysize)
		chunk_dron_enemigo = ds_grid_create(chunk_xsize, chunk_ysize)
		chunk_dron_aliado = ds_grid_create(chunk_xsize, chunk_ysize)
		chunk_edificios = ds_grid_create(chunk_xsize, chunk_ysize)
		chunk_edificios_enemigo = ds_grid_create(chunk_xsize, chunk_ysize)
		chunk_edificios_abandonado = ds_grid_create(chunk_xsize, chunk_ysize)
		chunk_edificios_estatico = ds_grid_create(chunk_xsize, chunk_ysize)
		chunk_edificios_dinamico = ds_grid_create(chunk_xsize, chunk_ysize)
		chunk_edificios_draw = ds_grid_create(chunk_xsize, chunk_ysize)
		chunk_edificios_background = ds_grid_create(chunk_xsize, chunk_ysize)
		chunk_edificios_dirty = ds_grid_create(chunk_xsize, chunk_ysize)
		ds_grid_clear(chunk_edificios_dirty, true)
		for(a = 0; a < chunk_xsize; a++)
			for(b = 0; b < chunk_ysize; b++){
				ds_grid_set(background, a, b, spr_hexagono)
				ds_grid_set(chunk_edificios_background, a, b, spr_hexagono)
				ds_grid_set(chunk_dron_enemigo, a, b, array_create(0, null_dron))
				ds_grid_set(chunk_dron_aliado, a, b, array_create(0, null_dron))
				ds_grid_set(chunk_edificios, a, b, array_create(0, null_edificio))
				ds_grid_set(chunk_edificios_enemigo, a, b, array_create(0, null_edificio))
				ds_grid_set(chunk_edificios_abandonado, a, b, array_create(0, null_edificio))
				ds_grid_set(chunk_edificios_estatico, a, b, array_create(0, null_edificio))
				ds_grid_set(chunk_edificios_dinamico, a, b, array_create(0, null_edificio))
				ds_grid_set(chunk_edificios_draw, a, b, array_create(0, null_edificio))
			}
		beta = ds_grid_create(xsize, ysize)
		ds_grid_clear(beta, null_beta)
		for(a = array_length(nucleos) - 1; a >= 0; a--){
			edificio = nucleos[a]
			edificio.coordenadas_dis = ds_grid_create(xsize, ysize)
			ds_grid_clear(edificio.coordenadas_dis, 0)
		}
	}
}