function save_edificio(buffer, edificio = control.null_edificio){
	with control{
		buffer_write(buffer, buffer_u8, real(edificio.input_index))
		buffer_write(buffer, buffer_u8, real(edificio.output_index))
		buffer_write(buffer, buffer_f16, real(edificio.proceso))
		buffer_write(buffer, buffer_bool, bool(edificio.start))
		for(var a = 0; a < rss_max; a++)
			buffer_write(buffer, buffer_f16, real(edificio.carga[a]))
		buffer_write(buffer, buffer_u8, real(edificio.carga_id))
		buffer_write(buffer, buffer_f16, real(edificio.carga_total))
		buffer_write(buffer, buffer_u16, real(edificio.fuel))
		buffer_write(buffer, buffer_bool, bool(edificio.waiting))
		buffer_write(buffer, buffer_bool, bool(edificio.idle))
		buffer_write(buffer, buffer_u16, real(edificio.link.punteros[0]))
		buffer_write(buffer, buffer_f16, real(edificio.vida))
		buffer_write(buffer, buffer_u16, real(edificio.target.punteros[0]))
		buffer_write(buffer, buffer_u16, real(edificio.target_edificio.punteros[0]))
		buffer_write(buffer, buffer_f16, real(edificio.flujo_consumo))
		buffer_write(buffer, buffer_f16, real(edificio.flujo_consumo_max))
		buffer_write(buffer, buffer_f16, real(edificio.energia_consumo))
		buffer_write(buffer, buffer_f16, real(edificio.energia_consumo_max))
		buffer_write(buffer, buffer_u16, real(edificio.edificio_index))
		buffer_write(buffer, buffer_bool, bool(edificio.luz))
		var len = array_length(edificio.procesador_link)
		buffer_write(buffer, buffer_u16, real(len))
		for(var a = 0; a < len; a++)
			buffer_write(buffer, buffer_u16, real(edificio.procesador_link[a].punteros[0]))
		buffer_write(buffer, buffer_bool, bool(edificio.eliminar))
		buffer_write(buffer, buffer_bool, bool(edificio.agregar))
		for(var a = 0; a < 13; a++)
			buffer_write(buffer, buffer_u16, real(edificio.punteros[a]))
		buffer_write(buffer, buffer_u8, real(edificio.outputs_carga_index))
	}
}
